# -*- coding: utf-8 -*-
"""Cox Proportional Hazard template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11BmDUfbUjb3zQqvDCvPXa_xWW6jzfmJb

#Libraries
"""

!pip install lifelines

#libraries
import pandas as pd
import statsmodels.api as sm

"""#Data Prep"""

#import the dataset
dataset = sm.datasets.get_rdataset("lung",
                                   package = "survival").data.dropna()
dataset.head()

#data organization
dataset.loc[dataset.status == 1, "status"] = 0
dataset.loc[dataset.status == 2, "status"] = 1

#get only variables needed
dataset = dataset.drop(columns = ["inst"])

"""# Cox Proportional Hazard"""

# Cox Proportional hazard
from lifelines import CoxPHFitter
model = CoxPHFitter()
model.fit(dataset, "time", event_col = "status")
model.print_summary()

#plotting
model.plot()