# -*- coding: utf-8 -*-
"""CPH challenge template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVcdcarPSk1RaNiZOzrmTl0TaBuJXflI

# Libraries and data
"""

!pip install lifelines

#libraries
import pandas as pd
import statsmodels.api as sm

#import the dataset
dataset = sm.datasets.get_rdataset("veteran",
                                   package = "survival").data
dataset.head()

"""# Cox Proportional Hazard"""

#transform string variables
dataset = pd.get_dummies(dataset, drop_first=True)

#check dependent variable
dataset.status.unique()

#Cox Proportional Hazard
from lifelines import CoxPHFitter
model = CoxPHFitter()
model.fit(dataset, "time", event_col = "status")
model.print_summary()

#plotting
model.plot()