# -*- coding: utf-8 -*-
"""Random Forest Challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UE8alojrE4eSuD_E_wA3-YCP5Rp7rbI0

# Libraries and data
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Data Mining for Business in Python 2021/7. Random Forest and Driver Importance

#libraries
import pandas as pd
import numpy as np

#get data
data = pd.read_csv("Affairs dataset.csv")
data.head()

"""#Data Prep"""

data.affairs.unique()

#isolate X and y
y = data.iloc[:, 1]
X = data.iloc[:, 2:]

#Transform Y
y = np.where(y>0,1,0)

#Transform occupation variable into dummy#
X = pd.get_dummies(X, drop_first=True, columns=['occupation'])
X.head()

#Transform string variables
X = pd.get_dummies(X, drop_first = True)
X.head()

"""# Random Forest and driver importance"""

#random forest
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10,
                               criterion="entropy",
                               random_state = 1502)
model.fit(X, y)

#feature importance
importance = pd.Series(model.feature_importances_,
                       index = X.columns.values).sort_values(ascending=False)
importance.nlargest(10).plot(kind='barh',
                             figsize = (12,8))