# -*- coding: utf-8 -*-
"""Random Forest and Feature Importance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_1uLJWxW7Ir07Qh7eaAgSkP3T9R3ShF

#Libraries and data
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Data Mining for Business in Python 2021/7. Random Forest and Driver Importance

#import libraries
import pandas as pd

#importing dataset
data = pd.read_csv("bank-full.csv", sep = ";")
data.head()

"""# Data Prep"""

#tranform categorical variables into dummy variables
dataset = pd.get_dummies(data = data,
                         drop_first = True)
dataset.head()

#isolate the x and y variables part 2
y = dataset.iloc[:, -1]
X = dataset.iloc[:, :-1]

#split dataset into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size =0.2,
                                                    random_state=1502,
                                                    stratify=y)

"""# Random Forest"""

#random forest
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=300,
                               criterion="entropy",
                               random_state = 1502)
model.fit(X_train, y_train)

#PRedictions
predictions = model.predict(X_test)
predictions[:20]

"""#Confusion Matrix"""

#Confusion MAtrix
from sklearn.metrics import classification_report
report = classification_report(y_test, predictions)
print(report)

"""# Feature Importance"""

#feature importance
importance = pd.Series(model.feature_importances_,
                       index = X_train.columns.values)
importance.nlargest(5).plot(kind='barh',
                             figsize = (12,8))