# -*- coding: utf-8 -*-
"""Gaussian Mixture Model challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KU3c_aIaSOnYHFlQiGV-vt55ZzPlIYDx

#Libraries and Data
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Data Mining for Business in Python 2021/Clustering - Gaussian Mixture Model

#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.mixture import GaussianMixture

#import dataset
dataset = pd.read_csv("Wine-quality-challenge.csv")
dataset.head()

"""# Clustering"""

#Optimal Clusters
n_components = np.arange(1, 10)
models = [GaussianMixture(n,
                          random_state = 1502).fit(dataset)
          for n in n_components]

plt.plot(n_components, 
         [m.bic(dataset) for m in models], 
         label='BIC')
plt.plot(n_components, 
         [m.aic(dataset) for m in models], 
         label='AIC')
plt.legend(loc='best')
plt.xlabel('n_components')

#Gaussian Mixture Model
model = GaussianMixture(n_components = 4,
                        random_state=1502).fit(dataset)

"""#Interpretation"""

#cluster interpretation
cluster_details = pd.DataFrame(model.means_,
                        columns = list(dataset.columns))
cluster_details